swagger: "2.0"
info:
  version: "0.1.0"
  title: Natural battle API
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /game:
    x-swagger-router-controller: game
    post:
      description: Updates a game and entries
      operationId: post
      parameters:
        - name: game
          in: body
          description: The game object
          required: true
          schema:
            $ref: "#/definitions/Game"
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/Game"
        "default":
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    get:
      description: Returns 'Game' info with all entries
      operationId: get
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/Game"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  Entry:
    type: object
    properties:
      id:
        type: integer
      progress:
        type: integer
  Game:
    type: object
    properties:
      level:
        type: integer
      entries:
        type: array
        items:
          $ref: '#/definitions/Entry'
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
